name: Bug Report
description: Report an issue to help us improve
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue please:
        - Check if the **Issues section** has a similar issue.
        - Read the directions [here](https://wiki.lineageos.org/how-to/bugreport)
        
        What not to report
        - Bugs in unofficial builds or anything not downloaded from our official portal
        - Missing Builds
        - Problems with the website
        - Asking for device support
        - Feature requests

        If you need help, please see https://wiki.lineageos.org/how-to/bugreport#android-bugs for more detailed instructions on how to report bugs or https://www.lineageos.org/community/ for ways to get in touch with the community.


  - type: input
    id: device
    attributes:
      label: Device
      description: |
        codename of the device you're using (ie: "mako", not "nexus 4")
      placeholder: "mako"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "LineageOS Version"
      description: "'Latest' is not a valid answer, please write the exact version number."
      placeholder: "lineage-20"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Build Date
      description: "Build date in YYYYMMDD format."
      placeholder: "20230322"
    validations:
      required: true

  - type: input
    id: kernel
    attributes:
      label: Kernel Version
      placeholder: "4.19.261-ga3e87045cf37"
    validations:
      required: true

  - type: input
    id: baseband
    attributes:
      label: Baseband Version
      placeholder: "AT31c7-00087-0713_1634_23a2dce"

  - type: input
    id: mods
    attributes:
      label: System Modifications
      placeholder: "google apps, magisk, etc"

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: dropdown
    id: directions
    attributes:
      label: "I have read the directions"
      description: "https://wiki.lineageos.org/how-to/bugreport"
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true

